apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app: pg
spec:
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - name: pg
        image: postgres
        args: ["-B", "4GB"]
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
      - name: pgq
        image: antonburtsev/pgq2
        #image: pgq:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 88
---
apiVersion: v1
kind: Service
metadata:
  name: pgq-ext
spec:
  type: NodePort
  ports:
  - port: 88
    nodePort: 30388
  selector:
    app: pg
---
apiVersion: v1
kind: Service
metadata:
  name: pg-ext
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30302
  selector:
    app: pg
