apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app: pg
spec:
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      nodeSelector:
        app: data
      containers:
      - name: pg
        image: postgres
        args: ["-B", "4GB", "-i"]
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgq-get
  labels:
    app: pgq-get
spec:
  selector:
    matchLabels:
      app: pgq-get
  template:
    metadata:
      labels:
        app: pgq-get
    spec:
      nodeSelector:
        app: get
      #initContainers:
      #- name: wait-pg
      #  image: busybox
      #  command: ["/bin/sh"]
      #  args: ["-c", "while ! nc -z pg 5432; do sleep 1; done"]
      containers:
      - name: pgq-get
        image: antonburtsev/pgq
        #image: pgq:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgq-put
  labels:
    app: pgq-put
spec:
  selector:
    matchLabels:
      app: pgq-put
  template:
    metadata:
      labels:
        app: pgq-put
    spec:
      nodeSelector:
        app: put
      #initContainers:
      #- name: wait-pg
      #  image: busybox
      #  command: ["/bin/sh"]
      #  args: ["-c", "while ! nc -z pg 5432; do sleep 1; done"]
      containers:
      - name: pgq-put
        image: antonburtsev/pgq
        #image: pgq:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgq-ext-get
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30300
  selector:
    app: pgq-get
---
apiVersion: v1
kind: Service
metadata:
  name: pgq-ext-put
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30301
  selector:
    app: pgq-put
---
apiVersion: v1
kind: Service
metadata:
  name: pg-ext
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30302
  selector:
    app: pg
---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  ports:
  - port: 5432
  selector:
    app: pg