apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgq
  labels:
    app: pgq
spec:
  replicas: 4
  serviceName: pgq
  selector:
    matchLabels:
      app: pgq
  template:
    metadata:
      labels:
        app: pgq
    spec:
      nodeSelector:
        pgq: data
      containers:
      - name: pg
        image: postgres
        args: ["-B", "16GB"]
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
      - name: pgq
        image: antonburtsev/pgq2
        ports:
        - containerPort: 88
